a = "PrOgRaMiZ".lower()
print(a)
a = "PrOgRaMiZ".upper()
print(a)
a = "This will split all words into a list".split()
print(a)
a = ' '.join(['This', 'will', 'join', 'all', 'words', 'into', 'a', 'string'])
print(a)
a = 'Happy New Year'.find('ew')
print(a)
a = 'Happy New Year'.replace('Happy','Brilliant')
print(a)